### ISSUE TITLE
Desenvolver User Story Manter Paciente

### ISSUE THREAD

**Issue by WesleyVitor** [joanmdrs/sigcli#42]
Nesta tarefa deve ser desenvolvido o user story manter paciente, conforme as especificações do analista @rauan-meirelles  .

Deve ser desenvolvido o frontend e o backend, conforme a arquitetura escolhida.

E é necessário que respeite os testes de aceitação que serão criados pelo analista @rauan-meirelles 

Obs.: Quando for desenvolver as páginas das funcionalidades, estas devem serem colocadas em um diretório chamado pages/patient. Pois iremos fazer uma refatoração do frontend para colocar rotas, aí vamos relacionar as rotas ao componentes desse diretório.

**Comment by allangbr** [comment]
Issue completamente desenvolvida.
Closes #42
