### ISSUE TITLE
Desenvolver User Story Manter Médico

### ISSUE THREAD

**Issue by WesleyVitor** [joanmdrs/sigcli#43]
Nesta tarefa deve ser desenvolvido o user story manter consulta, conforme as especificações do analista @joanmdrs  .

Deve ser desenvolvido o frontend e o backend, conforme a arquitetura escolhida.

E é necessário que respeite os testes de aceitação que serão criados pelo analista @joanmdrs 

Obs.: Quando for desenvolver as páginas das funcionalidades, estas devem serem colocadas em um diretório chamado pages/doctor. Pois iremos fazer uma refatoração do frontend para colocar rotas, aí vamos relacionar as rotas ao componentes desse diretório.

**Comment by adson-matheus** [comment]
- [X] Backend para Doctor
- [ ] Frontend para Doctor
